docs: translate english into japanese in docs of *.rs
SuteraVR/VanillaComponents pull request #4
Opened 2024-06-13 02:02 UTC by See2et

2024-06-13 22:21 UTC, AsPulse requested changes
おしごとはやいしーぜっと、すてき

2024-06-13 22:21 UTC, AsPulse commented on sutera-lib/src/signature/message.rs
> +    /// ## Parameters / パラメーター
```suggestion
    /// ## Parameters / 引数
```

2024-06-13 22:21 UTC, AsPulse commented on sutera-lib/src/signature/message.rs
> +    /// 署名者の署名鍵でメッセージを署名する。
```suggestion
    /// Sign a message with the [`author`]'s signing key.
    /// [`author`]の署名鍵でメッセージを署名する。
```
構造体内の具体的なプロパティ名を指してるやつは訳さないでOK！
(今回はもともとの英文がプロパティを参照する表記になってなかったので my fault ですごめんね……一緒に直しておいてくれるとありがたい)

2024-06-13 22:21 UTC, AsPulse commented on sutera-lib/src/signature/message.rs
> +    /// TODO: assertionの良い和訳がわかりません！
そういう時は公式ドキュメントを見ましょう.ᐟ.ᐟ.ᐟ
https://doc.rust-jp.rs/book-ja/ch11-01-writing-tests.html

<img width="630" alt="image" src="https://github.com/SuteraVR/VanillaComponents/assets/84216737/28b74313-b3f0-43a1-b748-409d07b4e868">

「アサーション」とそのまま書いてあるので、それと同じでよいと思います (TODO消しといてね)

2024-06-14 22:32 UTC, AsPulse commented
な、なんか一箇所しかなおってないかも……

2024-06-14 22:41 UTC, See2et commented
これでどうでしょう！

2024-06-14 23:03 UTC, AsPulse approved these changes
いい感じ〜！！

2024-06-14 23:04 UTC, merged